// This is just auto-generated by Angular CLI
// Do not modify this file
import { SecondaryModule } from './secondary.module';

describe('SecondaryModule', () => {
  let secondaryModule: SecondaryModule;

  beforeEach(() => {
    secondaryModule = new SecondaryModule();
  });

  it('should create an instance', () => {
    expect(secondaryModule).toBeTruthy();
  });
});
