// This is just auto-generated by Angular CLI
// Do not modify this file
import { TestBed, inject } from '@angular/core/testing';

import { MonitorDbService } from './monitor-db.service';

describe('MonitorDbService', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [MonitorDbService]
    });
  });

  it('should be created', inject([MonitorDbService], (service: MonitorDbService) => {
    expect(service).toBeTruthy();
  }));
});
