// This is just auto-generated by Angular CLI
// Do not modify this file
import { TestBed, inject } from '@angular/core/testing';

import { MyAPIService } from './my-api.service';

describe('MyAPIService', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [MyAPIService]
    });
  });

  it('should be created', inject([MyAPIService], (service: MyAPIService) => {
    expect(service).toBeTruthy();
  }));
});
